# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课程添加时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': '章节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='课程名')),
                ('description', models.CharField(max_length=100, verbose_name='课程描述')),
                ('degree', models.CharField(choices=[('CJ', '初级'), ('ZJ', '中级'), ('GJ', '高级')], max_length=10)),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('students_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('category', models.CharField(max_length=20, verbose_name='课程类别')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程图片')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课程添加时间')),
                ('recommend', models.BooleanField(default=False, max_length=2, verbose_name='是否推荐')),
                ('has_favor', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('notice', models.CharField(default='', max_length=200, verbose_name='课程须知')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='资料名称')),
                ('download', models.FileField(upload_to='course/download/%Y/%m', verbose_name='下载')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course')),
            ],
            options={
                'verbose_name': '课程资源下载',
                'verbose_name_plural': '课程资源下载',
                'db_table': '课程资源下载',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='教师图片')),
                ('work_year', models.IntegerField(blank=True, null=True, verbose_name='工作年限')),
                ('introduction', models.CharField(max_length=100, verbose_name='教师描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, max_length=20, verbose_name='添加时间')),
                ('nick_name', models.CharField(default='', max_length=10, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
                'db_table': '教师',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='视频名')),
                ('url', models.URLField(verbose_name='视频链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课程添加时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': '视频',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Teacher', verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course', verbose_name='所属课程'),
        ),
    ]
