# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='视频链接'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
