# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180917_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
